### ISSUE TITLE
switchinput  inside collapse widget

### ISSUE THREAD

**Issue by diesonne** [kartik-v/yii2-widget-switchinput#13]
When using the switchinput inside a collapse widget the switch does not get initialised with the model value. On submitting the form the value does not get saved.

```php
echo yii\bootstrap\Collapse::widget([
  'items' => [
    [
      'label'   => 'test',
      'content' => $form->field($model, "[5]value")
        ->widget(kartik\widgets\SwitchInput::className())
        ->label($model->name),
    ]
  ]
]);
```

when i use the same code without a collapse widget there is no problem.

On inspecting the code i can see there is a hidden field (with the correct value) and an input type checkbox with the wrong value

**Comment by kartik-v** [comment]
Relates to #12. Upgrade to latest release (this was a problem with source plugin and the author has fixed it in the later release)

**Comment by diesonne** [comment]
This is what I have in composer: 
"kartik-v/yii2-widgets": "*",

and the changelog.md file's last update is about v1.2.0

i deleted all folders in /web/assets

problem persists

**Comment by diesonne** [comment]
upon checking the assets/js/bootstrap-switch.js this seems to be an older version ... odd that composer did not update this

**Comment by diesonne** [comment]
never mind, found the issue, there is no release yet for V1.3.0... i'll wait for that
