### ISSUE TITLE
Render problem with ajax loaded content

### ISSUE THREAD

**Issue by infoweb-internet-solutions** [kartik-v/yii2-widget-switchinput#14]
I have a form whose html content changes when the value of a specific dropdown changes. The new html content that contains a couple of switchinput widgets is loaded with ajax and injected in the form. The problem is that the widgets are not rendered but checkboxes are shown instead. If i then save the state of the form and reload the page, the widgets are rendered correctly.

**Comment by dubeymahi48** [comment]
I have same problem with other widgets but i am also not able to resolve it.
As i am research this problem is comes because of inject jquery and bootstrap again into view with renderAjax(). 

So please help us..
Thanks...

**Comment by kartik-v** [comment]
Note when you are using ajax to overwrite HTML markup - you will be erasing any widgets being rendered via jquery plugins and also all its events. That's why you will see plain inputs - because the javascript for initializing these are not called when you just overwrite the HTML.

You would need to reinitialize every jquery plugin with its properties after the ajax call completes to ensure this works. Using `renderAjax` method may help in various cases - but in other cases you would need to reinitalize the plugin.

**Comment by dubeymahi48** [comment]
@kartik-v  thank you for quick response.
How can i reinitialize plugin with renderAjax() as DepDrop widget or FileInput widget???

**Comment by gsalgadotoledo** [comment]
Hello @kartik-v how can I do? reinitialize plugin, Thanks!

**Comment by adriandrozdz** [comment]
My solution is this.
Create callback of some kind and insert this function:
```javascript
jQuery(".switch-input-button").bootstrapSwitch({
            'onColor': "success",
            'offColor': "danger",
            'onText': "No",
            'offText': "Yes"
        });
```javascript
Where ".switch-input-button" class is added in options while creating widget
like here

```php
<?= $form->field($modelOpendaysItem, "[{$i}]opendays_item_metro")
                                        ->widget(SwitchInput::classname(), [
                                            'options' => [
                                                'class' => 'switch-input-button'
                                            ],
                                            'pluginOptions' => [
                                                'onColor' => 'success',
                                                'offColor' => 'danger',
                                                'onText' => 'Tak',
                                                'offText' => 'Nie',
                                            ]
                                    ]) ?>
```

**Comment by kartik-v** [comment]
Render widget inside yii Pjax container and set the `SwitchInput` widget's `pjaxContainerId` property o to the pjax container identifier.

**Comment by dev1-kait** [comment]
`<?= $form->field($model, 'description')->widget(Summernote::classname(), [
                        'options' => ['placeholder' => 'Edit your blog content here...']
]); ?>`

it's working for all widgets but not for Summernote
