### ISSUE TITLE
width issue

### ISSUE THREAD

**Issue by michaelnguyen547** [kartik-v/yii2-widget-switchinput#17]
sometimes the switch input width does not fully expand , it is very small. A page refresh will fix, but the issue come up very often. 

![switch-input](https://cloud.githubusercontent.com/assets/436950/9096516/cfa5b088-3b7a-11e5-86c1-288507717ffc.png)

``` php
<?= $form->field($model, 'is_billable', [ 'options' => ['class' => 'col-md-2']])
->widget(SwitchInput::classname(), [
      'type' => SwitchInput::CHECKBOX,
       'pluginOptions' => [
            'size' => 'large',
             'onColor' => 'success',
             'offColor' => 'danger',
       ]
]); ?>

```

**Comment by dadinugroho** [comment]
Is there any fix for this yet?

**Comment by Webkadabra** [comment]
I'm having this issue as well - for me it appears almost every time (first load) when loading in modal something that has SwitchInput.

**Comment by akorinek** [comment]
Same for me, strange thing is I have one switchinput in a modal form since a year and that one always works, I added two new ones and those don't. In rare cases they do, no idea what's triggering this. Basically something is calculating the width too narrow.

**Comment by kartik-v** [comment]
seems to be some css calculation issue by the plugin... if you have an use case, can you report it to the plugin author and see if there is a fix?

**Comment by jainabhishek14** [comment]
This issue always occurs on Chrome 53.0.2785.143 64 bit. Not sure about other versions.

**Comment by Commifreak** [comment]
This issue still persists.

1st try:

![ok](https://cloud.githubusercontent.com/assets/87267/24901495/895dc216-1ea7-11e7-9337-5cce72f1dc35.JPG)

2nd:

![nok](https://cloud.githubusercontent.com/assets/87267/24901500/8edabf46-1ea7-11e7-8d00-9735c2d04495.JPG)


All up-to-date, would be great if this gets addressed.

Sample Code:

```php
	[
		'attribute' =>'status',
		'type' => DetailView::INPUT_SWITCH,
		'format' => 'raw',
		'value' => $model->status ? 
			'<span class="label label-success">Active</span>' : 
			'<span class="label label-danger">Inactive</span>',
		'widgetOptions' => [
			'pluginOptions' => [
				'onText' => 'Active',
				'offText' => 'Inactive',
				],
		],
	],
```

**Comment by bogdik** [comment]
Fix this bug
I add new parameters: handleWidth,labelWidth,staticWidth
Example use in widget:
        'handleWidth'=>'53',
        'labelWidth'=>'77',
        'staticWidth'=>'53'
![2017-05-23 14-03-15](https://cloud.githubusercontent.com/assets/15012904/26351746/86075e84-3fc1-11e7-8b75-1e3744a7843f.png)

**Comment by leoncesar** [comment]
I solved it with **SwitchInputAsset**
`use kartik\switchinput\SwitchInputAsset; `

And at the end of the file:
`SwitchInputAsset::register($this);`

If the **SwitchInput** is on a **Modal** you have to register the asset on the main view (the modal container view)

**Comment by dhwywy** [comment]
Thank you!!!
This trick with SwitchInputAsset works perfectly.

**Comment by enkr1** [comment]
> I solved it with **SwitchInputAsset**
> `use kartik\switchinput\SwitchInputAsset; `
> 
> And at the end of the file:
> `SwitchInputAsset::register($this);`
> 
> If the **SwitchInput** is on a **Modal** you have to register the asset on the main view (the modal container view)

Perfect answer!
