### ISSUE TITLE
clicking the label activates the switch

### ISSUE THREAD

**Issue by diesonne** [kartik-v/yii2-widget-switchinput#24]
is there a way to not make the label clickable? 

(this behaviour is only present when used with a model and activeform)

**Comment by R13e** [comment]
I have to push the question. I have a switch that is _disabled_ to prevent a user to click on them, but unfortunately clicking the label triggers the event.

**Comment by kartik-v** [comment]
Set the `for` attribute for the `label` in `labelOptions` to null / false.

**Comment by R13e** [comment]
Thanks a lot! I ended up with this (using Switch Input in [FormGrid](https://github.com/kartik-v/yii2-builder/)):

    echo FormGrid::widget([
        'model' => $model,
        'form' => $form,
        'autoGenerateColumns' => true,
        'rows' => [
            [
                'attributes' => [
                    'approval' => [
                        'fieldConfig' => ['labelOptions' => ['for' => false]],
                        'type' => Form::INPUT_WIDGET,
                        'widgetClass' => 'kartik\widgets\SwitchInput',
                        'options' => [
                            'readonly' => true,
                            'type' => 1,
                            'pluginOptions' => [
                                'size' => 'med',
                                'onColor' => 'success',
                                'offColor' => 'danger',
                                'onText' => 'Ja',
                                'offText' => 'Nein',
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ]);
