### ISSUE TITLE
SwitchInput in modal

### ISSUE THREAD

**Issue by destyl** [kartik-v/yii2-widget-switchinput#26]
Hi,
when i add Switchinput in modal, which is loaded by renderAjax - it's broken like photo below. Sometimes it work fine, but generally it's borken.

![zrzut ekranu z 2017-02-22 10-27-35](https://cloud.githubusercontent.com/assets/15036507/23205274/9197776c-f8e9-11e6-8264-4156ed71260b.png)

**Comment by wskeee** [comment]
me too!
My solution：
1、create a simple switchInput in parent,that will be work.
2、or use SwitchInputAsset::register($view); in the parent.

hope fix that!!!

**Comment by destyl** [comment]
@wskeee second solution is the clearest one I guess, nevertheless that worked! Thanks! :)

**Comment by makaronnik** [comment]
It worked for me! Many thanks!
