### ISSUE TITLE
disabled save wrong value

### ISSUE THREAD

**Issue by DPineault** [kartik-v/yii2-widget-switchinput#34]
I'm using the switchinput as follows

```
	$form->field($model, 'Active',
	[
		'inputOptions' => [
			'value' => Yii::$app->formatter->asInteger($model->Active), 
			'class' => 'form-control',
		],
		'labelOptions' => ['class' => 'control-label'],
		'horizontalCssClasses' => [
			'class' => '',
			'wrapper' => '',
		],
		'template' => '<div class="col-sm-2">{label}</div><div class="col-sm-4">{input}{error}</div>',
	])
	->widget(SwitchInput::classname(), 
	[
		'options'=>[
			'tabIndex'=>'345',
		],
		'pluginOptions' => [
			'size' => 'small',
			'onText' => 'Yes',
			'offText' => 'No',
			'onColor' => 'success',
			'offColor' => 'danger',
		],
		'disabled' => (Yii::$app->user->can('Administrator') ? false : true),
	])
```

If the use is Administrator, everything works just fine, but, if not, then when the form loads, it displays the value correctly, but always saves all values as No/0, even if it was displaying Yes/1.

My workaround has been to add javascript before submit to enable all controls.

**Comment by craiglondon** [comment]
@DPineault If the input is "disabled" then any change to it is not submitted to the form.  I would suggest to use readonly instead of disabled.

**Comment by kartik-v** [comment]
Correct @craiglondon
